version: '3.8'

services:
  servidor:
    build:
      context: ./servidor  # Caminho para o diret칩rio onde est치 o Dockerfile do servidor
      dockerfile: Dockerfile  
    container_name: cont-servidor
    ports:
      - "8080:8080"
    volumes:
      - /mnt/wsl/Ubuntu/codes/my-app-redes/servidor/trechos_viagens.json:/data/trechos_viagens.json
    networks:
      - mynetwork

    stdin_open: true  # Similar ao -i
    tty: true

  cliente:
    build:
      context: ./cliente  # Caminho para o diret칩rio onde est치 o Dockerfile do cliente
      dockerfile: Dockerfile 
    networks:
      - mynetwork

    stdin_open: true  # Similar ao -i
    tty: true

networks:
   mynetwork:
     driver: bridge
